window.tyrano_lang = {
    word: {
        go_title: "Return to the title screen?",
        exit_game: "Close the window and quit the game?",
        not_saved: "No save data available.",
        confirm: "Confirm",
        confirm_beforeunload: "You have unsaved progress. Are you sure you want to quit?",
        tag: "Tag",
        not_exists: " does not exist.",
        error: "An error occurred. Please check the script.",
        label: "Label",
        label_double: " is duplicated in the same scenario file.",
        error_occurred: "An error occurred.",
        save_file_violation_1: "This save data appears to have been moved. Do not load it unless you trust its source.",
        save_file_violation_2: "Load this save data and start the game?",
        save_file_violation_3: "Startup was canceled. Delete the save data and try again.",
        double_start: "The game is already running and cannot be started twice.",
        reload: "Reload",
        line: "Line { line }",
        initialized_saved_data: "Save data has been initialized.",
        initializing_saved_data: "Initialize the save data?",
        saved_data_is_corrupted: "The save data may be corrupted. Initialize it?",
        save_does_not_work: "Saving is unavailable in this environment. This may occur when running the game locally.",
        undefined_tag: 'Tag "{ name }" is not defined.',
        undefined_label: 'Label "{ name }" is not defined.',
        undefined_character: 'Character "{ name }" is not defined. Define it with [chara_new].',
        undefined_face: 'Expression "{ face }" is not defined for character "{ name }". Define it with [chara_face].',
        undefined_character_parts: 'Layered parts are not defined for character "{ name }". Define them with [chara_layer].',
        undefined_keyframe: 'Keyframe animation "{ keyframe }" is not defined.',
        undefined_3d_model: '3D model "{ name }" is not defined.',
        preload_failure_sound:
            'Audio file "{ src }" was not found. Was a full path specified?\n\n(Valid example) ./data/bgm/my_bgm.mp3',
        preload_failure_image:
            'Image file "{ src }" was not found. Was a full path specified?\n\n(Valid example) ./data/image/my_image.png',
        preload_failure_video:
            'Video file "{ src }" was not found. Was a full path specified?\n\n(Valid example) ./data/video/my_video.mp4',
        invalid_keyframe: "The keyframe value is invalid.",
        invalid_keyframe_percentage:
            'The percentage "{ percentage }" in the keyframe is invalid. Use a value such as "0%" or "30%".',
        error_in_iscript: "An error occurred inside [iscript].",
        missing_endif: "No [elsif], [else], or [endif] was found after [if], or the [if] block contains too many tags.",
        missing_endmacro: "No [endmacro] was found after [macro], or the macro contains too many tags.",
        missing_endignore: "No [endignore] was found after [ignore], or the ignore block contains too many tags.",
        missing_parameter: 'Parameter "{ param }" is required for tag "{ tag }".',
        if_and_endif_do_not_match: "The numbers of [if] and [endif] tags do not match.",
        unsupported_extensions: 'The file format "{ ext }" is not supported.',
        undefined_keyconfig:
            'Key configuration is not defined. KeyConfig.js may be missing or contain a syntax error. Check for missing commas "," or brackets "]" and "}".',
        compensate_missing_quart:
            'An unexpected "]" was detected, possibly because a parameter quote is missing. The script will be corrected automatically.\n\nBefore: { before }\nAfter: { after }',
        duplicate_label:
            'Label "{ name }" is duplicated in the same scenario file. Label names must be unique within each scenario file.',
        file_not_found: "File not found.\n\n{ path }",
        patch_not_found: "Patch file not found.\n\n{ path }",
        new_patch_found: "A new update is available.\n\nVersion: { version }\n{ message }\n\nApply the update?",
        apply_web_patch: "The update will be applied. The game will close automatically when it is complete.",
        apply_patch_complete: "The update has been applied. Please restart the game.",
        resume_game: "Game resumed.",
    },

    novel: {
        file_menu_button_save: "menu_button_save.gif",
        file_menu_button_load: "menu_button_load.gif",
        file_menu_button_message_close: "menu_message_close.gif",
        file_menu_button_skip: "menu_button_skip.gif",
        file_menu_button_title: "menu_button_title.gif",
        file_menu_button_close: "menu_button_close.png",
        file_menu_bg: "menu_bg.jpg",
        file_save_bg: "menu_save_bg.jpg",
        file_load_bg: "menu_load_bg.jpg",
        file_button_menu: "button_menu.png",
    },
};
